<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_enfold_child_lottie__fields',
	'title' => 'Lottie Fields',
	'fields' => array(
		array(
			'key' => 'enfold_child_lottie__json',
			'label' => 'JSON',
			'name' => 'json',
			'type' => 'file',
			'instructions' => 'Upload the Lottie JSON file, make sure the Lottie animation is cropped as much as possible.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => 'json',
		),
		array(
			'key' => 'enfold_child_lottie__w',
			'label' => 'Width',
			'name' => 'width',
			'type' => 'text',
			'instructions' => 'Input the width of the Lottie animation (no px), this will not affect the display of the Lottie instance but it is needed for placeholder calculations. If width and height are the same (square), leave both empty.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'enfold_child_lottie__h',
			'label' => 'Height',
			'name' => 'height',
			'type' => 'text',
			'instructions' => 'Input the height of the Lottie animation (no px), this will not affect the display of the Lottie instance but it is needed for placeholder calculations. If width and height are the same (square), leave both empty.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => '',
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'enfold_child_lottie__fallback_image',
			'label' => 'Fallback Image',
			'name' => 'fallback_image',
			'type' => 'image',
			'instructions' => 'Non-required, upload a fallback image for this Lottie, not in use right now as IE support has been dropped, may be used in the future.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'lottie_animation',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;